#!/bin/sh

tell()
{
  echo $1
}

handler()
{
  welcome
}

welcome()
{
  tell "Welcome!"
  handler()
  {
    name
  }
}

name()
{
  tell "What is your name?"
  read name
  tell "Hi, $name"
}

while true 
do
  read raw
  handler
done
